name: Deploy ke Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI (Versi Stabil)
        run: npm install -g firebase-tools@12.9.1

      - name: Jalankan Deploy
        run: firebase deploy --project apk-silat --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive