name: Deploy ke Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Kita tambahkan baris ini untuk mempercepat proses
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.TESAPKSILAT99 }}'
          projectId: tesapksilat99
          channelId: live
          # Tambahkan ini untuk bypass proses build yang tidak perlu
          skipBuild: true