name: Deploy ke Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Jalankan Deploy
        run: firebase deploy --only hosting --project apk-silat --token "${{ secrets.FIREBASE_TOKEN }}"